### PR TITLE
add @available to ConstraintLayoutGuide extension

### PR DESCRIPTION
**Pull request by LiVincent-Zhang**
It seems that without @available(iOSApplicationExtension 9.0, *) above the ConstraintLayoutGuide extension the instance of ConstraintLayoutGuide have no member named "makeConstraints".

I use SnapKit in latest release XCode8 and swift3

### CODE REVIEW

**Comment by robertjpayne** [comment]
@LiVincent-Zhang thanks for this PR does it not work with `@available(iOS 9.0, *)`? I don't think it should use the `iOSApplicationExtension` part?

**Comment by robertjpayne** [comment]
@LiVincent-Zhang gah sorry it also needs macOS support so should be:

`@available(iOS 9.0, OSX 10.11, *)` and also a bit lower in the file there is a `#available(iOS 9.0, *)` that needs to be updated to `#available(iOS 9.0, OSX 10.11, *)`

**Comment by LiVincent-Zhang** [comment]
OKay. the error of CI is confused me. Orz..
