### ISSUE TITLE
'SnapKit.ConcreteConstraint' does not implement methodSignatureForSelector

### ISSUE THREAD

**Issue by tommi** [SnapKit/SnapKit#84]
Making constraints in a UICollectionViewCell's `override init(frame: CGRect)` causes a crash on a iPad Mini with iOS 8.2. The same code works on a iPad Air iOS 8.3. Constraints are added to a child view of the contentView.

Console log:
`*** NSForwarding: warning: object 0x16d13270 of class 'SnapKit.ConcreteConstraint' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[SnapKit.ConcreteConstraint superview]`

SIGABRT happens on https://github.com/SnapKit/SnapKit/blob/0.10.0/Source/Constraint.swift#L302

**Comment by robertjpayne** [comment]
@tommi any chance you can share a more complete stack trace or code that is setting up the constraints?

**Comment by tommi** [comment]
@robertjpayne  sure! It's somewhat like this:

```
class AdventureCell: UICollectionViewCell {
    override init(frame: CGRect) {
        super.init(frame: frame)

        contentView.addSubview(label)
              
        label.snp_remakeConstraints {
            (make) -> Void in
            make.right.equalTo(self.contentView).offset(-12)
            make.height.equalTo(20)
            make.left.equalTo(self.contentView.snp_centerX).offset(2)
            make.bottom.equalTo(self.contentView).offset(-12)
        }
    }
}
```

#0	0x311fadf0 in __pthread_kill ()
#1	0x3127ac96 in pthread_kill ()
#2	0x31199938 in abort ()
#3	0x0085f77e in swift::fatalError(char const*, ...) ()
#4	0x0085fcce in -[SwiftObject doesNotRecognizeSelector:] ()
#5	0x22b87948 in ___forwarding___ ()
#12	0x26179e54 in -[UIView(UIConstraintBasedLayout) addConstraints:] ()
#13	0x00594764 in function signature specialization <Arg[0] = Exploded, Arg[1] = Owned To Guaranteed> of SnapKit.ConcreteConstraint.installOnView (SnapKit.ConcreteConstraint)(updateExisting : Swift.Bool) -> Swift.Array<SnapKit.LayoutConstraint> at /.../Carthage/Checkouts/SnapKit/Source/Constraint.swift:302
#14	0x00591140 in SnapKit.ConcreteConstraint.installOnView (SnapKit.ConcreteConstraint)(updateExisting : Swift.Bool) -> Swift.Array<SnapKit.LayoutConstraint> at /.../Carthage/Checkouts/SnapKit/Source/Constraint.swift:194
#15	0x005aaad0 in static SnapKit.ConstraintMaker.remakeConstraints (SnapKit.ConstraintMaker.Type)(ObjectiveC.UIView, closure : (make : SnapKit.ConstraintMaker) -> ()) -> () at /.../Carthage/Checkouts/SnapKit/Source/ConstraintMaker.swift:165
#16	0x000b475c in Project.CoverCell.updateConstraints (Project.CoverCell)() -> () at ProjectViewController.swift:83
#17	0x000b5094 in @objc Project.CoverCell.updateConstraints (Project.CoverCell)() -> () ()
#18	0x266b81ea in -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] ()

**Comment by robertjpayne** [comment]
@tommi hmm so strange especially since it works on 8.3 just fine.

If you alter what constraints you're making does it help at all? It's just really hard to try and narrow this down from my end.

**Comment by tommi** [comment]
@robertjpayne yeah, I understand. No luck with altering constraints for example to absolute values. I can't reproduce the issue with available iOS 8.2 simulators (iPad 2, iPad Air, iPad Retina), only with actual iOS 8.2 devices (currently iPad mini, iPhone 5). Works device and simulator on iOS 8.3.

I'll try narrowing it down further.

**Comment by robertjpayne** [comment]
@tommi  can you try out develop branch? I removed all the final declarations as someone else is having a very strange issue related to them too.

I don't have a 8.2 device to test on at the moment.

**Comment by hemantasapkota** [comment]
For me switching to **develop** fixed a similar error that I was getting. Details below:
```
*** NSForwarding: warning: object 0x15d930e0 of class 'SnapKit.ConcreteConstraint' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[SnapKit.ConcreteConstraint superview]
```

**Comment by robertjpayne** [comment]
@hemantasapkota sounds good – seems like the `final` classifier I put on everything has caused some weird issues.

**Comment by tommi** [comment]
@robertjpayne works with the develop branch and iOS 8.2 device :)

**Comment by robertjpayne** [comment]
@tommi awesome news! Looks like it's best to stay away from `final` for now.

**Comment by robertjpayne** [comment]
SnapKit 0.11.0 is pushed to cocoapods trunk and master. Thanks for reporting this again and testing!

**Comment by st3fan** [comment]
I can reproduce this crash on release builds on a iPod Touch with 8.3 and 4S with 8.3. With SnapKit 0.10.

Is it known if this fix made it in the 0.11 release? Or should I use the develop branch for now?
